#!/bin/bash

set -euo pipefail
IFS=

usage () {
    echo "usage: $0 outputfile.out"
    echo "  compare outputfile.out against outputfile.actual.out,"
    echo "  the former being part of the project repository, "
    echo "  the latter the actual output from a test. Report "
    echo "  test failure via diff and exit code."
    false
}

if [ $# -ne 1 ]; then usage; fi

outputfile_out="$1"
outputfile=$(echo "$outputfile_out" | sed 's/\.out$//')

# like in g++ call in Makefile, force color so that it is maintained
# when piping to less

colordiff () {
    if [ -z "${INSIDE_EMACS-}" ]; then
	diff --color=always "$@"
    else
	diff "$@"
    fi
}

# With HACK to revert the green and red coloring (couldn't figure out
# how to use the --palette argument, man man).

colordiff -u "$outputfile_out" "$outputfile.actual.out" | \
    perl -wne '
BEGIN {
    $red= "\x1b\x5b\x33\x31\x6d";
    $tmp= "gqn3qpzggn".rand;
    $green= "\x1b\x5b\x33\x32\x6d";
}
s/\Q$red/$tmp/sg;
s/\Q$green/$red/sg;
s/\Q$tmp/$green/sg;
print or die $!'
